ThibautBaissac/book_a_boat

Gemfile, Gemfile.lock, app/models/booking.rb, app/models/ship.rb, app/models/user.rb, app/views/layouts/application.html.erb, config/environments/development.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20210816125947_devise_create_users.rb, db/migrate/20210816130635_create_ships.rb, db/migrate/20210816132029_add_name_to_user.rb, db/migrate/20210816133030_create_bookings.rb, db/schema.rb, test/models/booking_test.rb, test/models/ship_test.rb, test/models/user_test.rb
Hi I added the models lol, Booking User and Ship
=> added models

app/models/ship.rb, app/models/user.rb, db/migrate/20210816135244_add_column_to_user.rb, db/schema.rb
Model validations and added column
=> validations and add column to user

app/controllers/ships_controller.rb, config/routes.rb, test/controllers/ships_controller_test.rb
=> Added ship controller

app/views/bookings/index.html.erb
Add empty booking folder to views
=> Add booking folder to views

app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_colors.scss
Added the right colors int the config scss file
=> Updated config colors

app/views/ships/index.html.erb
Hello I did the basic frame of the ships index page 🚢🚢🚢
=> basic frame of ships index

db/migrate/20210817041700_add_column_to_ships.rb, db/schema.rb, db/seeds.rb
=> Add ship description

app/views/shared/_carousel.html.erb, app/views/ships/show.html.erb
Un proposition de design pour la ship/:id (show)
=> Ship : show + carousel

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/pages_controller.rb, app/controllers/ships_controller.rb, app/policies/application_policy.rb, app/policies/ship_policy.rb, app/views/pages/home.html.erb, app/views/ships/show.html.erb, test/policies/ship_policy_test.rb
=> pundit + devise

app/views/bookings/new.html.erb, app/views/shared/_carousel.html.erb, app/views/ships/index.html.erb, app/views/ships/show.html.erb, package.json, yarn.lock
Fixed the button paths in show and index, and started building the new booking
=> fixed paths in show and index, and started working on new booking

db/seeds.rb
adding team as new users of the app
=> new users created

db/seeds.rb
=> adding new ships

app/controllers/bookings_controller.rb, app/policies/booking_policy.rb, test/policies/booking_policy_test.rb
=> Add pundit: Booking new

app/assets/stylesheets/components/_navbar.scss, app/javascript/components/_navbar.js, app/javascript/packs/application.js, app/views/shared/_navbar.html.erb
Log out not working (stays log out, does not change in sign in ...)
=> Added links on navbar btn

app/assets/stylesheets/components/_navbar.scss, app/javascript/components/_navbar.js, app/javascript/packs/application.js, app/views/shared/_navbar.html.erb
Buttons functionnal + Added js on navbar background on scroll
=> Buttons functionnal + Added js on navbar background on scroll

app/controllers/ships_controller.rb, app/policies/ship_policy.rb, app/views/ships/new.html.erb
Added authentication for new and create Ships, and added create ship feature
=> New ship form

app/controllers/ships_controller.rb, app/policies/ship_policy.rb, app/views/pages/dashboard.html.erb, app/views/ships/edit.html.erb
Added delete update and edit authorizations, and created the form to update and delete owner ships
=> added authorizations and edit/delete for ships

app/controllers/ships_controller.rb
changed update and delete paths
=> changed update and delete paths

app/views/shared/_modal_delete_confirmation.html.erb, app/views/ships/edit.html.erb
Modal to confirm ship deletion
=> Modal to confirm ship deletion

app/views/ships/show.html.erb
fixed icons on ships#show and added margins to button and form
=> fixed ships show

app/views/pages/dashboard.html.erb
Added profile details and bootstrap to dashboard profile
=> Edit dashboard profile

app/assets/stylesheets/components/_banner.scss, app/controllers/pages_controller.rb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb
=> Added search-bar to the banner on homepage

app/assets/stylesheets/components/_banner.scss, app/views/pages/home.html.erb
=> Added slogan on homepage

.gitignore, Gemfile, Gemfile.lock
=> Dotenv and Cloudinary

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
Changed btn position and added responsive on the navbar button and brand
=> Changes on navbar buttons

db/seeds.rb
adding 2 descriptions to ships to test
=> adding-descriptions-to-ships

app/views/ships/show.html.erb
Fixed the date picker to book on ship#show
=> fixed date picker on booking

app/controllers/application_controller.rb, app/controllers/users/confirmations_controller.rb, app/controllers/users/omniauth_callbacks_controller.rb, app/controllers/users/passwords_controller.rb, app/controllers/users/registrations_controller.rb, app/controllers/users/sessions_controller.rb, app/controllers/users/unlocks_controller.rb
I fixed the login to reroute to dashboard
=> fixed login re-route

app/views/ships/edit.html.erb, app/views/ships/new.html.erb
added dropdown for ship categories
=> added dropdown to add and edit ship

app/views/shared/_carousel.html.erb
fixing bug in path carroussel image cause we create images/ships folder
=> fixing bug in path carroussel image

app/controllers/bookings_controller.rb
after booking, user routed to dashboard
=> bookings route

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_navbar.scss, app/views/shared/_carousel.html.erb, app/views/ships/show.html.erb
=> Changed booking in sticky card and added navbar shadow

app/javascript/components/_tab.js, app/javascript/packs/application.js, app/views/pages/dashboard.html.erb
Booking is the active tab in dashboard instead of profile
=> Added active tab booking in dashboard

app/views/ships/index.html.erb
changed list of ships to list of "category" and added margin top
=> list of ships

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_navbar.scss, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
=> Removed lease btn from navabr and added a card instead

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/views/layouts/application.html.erb, app/views/shared/_footer.html.erb
=> Added footer

app/views/ships/index.html.erb
Changes list of ships by the category of the ships or by a sorry message if no ship
=> Changed title on index by category 

app/assets/stylesheets/components/_banner.scss, app/views/pages/home.html.erb
=> Removed dates from search bar

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
added dropdown bar and a the smallest bit of css
=> added dropdown

app/views/pages/dashboard.html.erb
the name of the branch is wrong lol, I added the "add a boat" button to the dashboard
=> added add a boat to dash

app/controllers/bookings_controller.rb, app/policies/booking_policy.rb, app/views/pages/dashboard.html.erb
added a button to delete bookings, and redirected delete path
=> added delete booking and redirected delete

app/views/pages/home.html.erb
=> testimonial-no-lorem

app/views/pages/dashboard.html.erb, app/views/ships/show.html.erb
changed ships to "my ships" and redirected ships#show to dashboard if the user is the owner of the ship
=> fixed show button to correspond to user

app/controllers/application_controller.rb, app/models/user.rb, app/views/devise/registrations/new.html.erb, app/views/shared/_navbar.html.erb, db/migrate/20210819113037_add_column_to_users.rb, db/schema.rb
User without avatar:
User with avatar:
=> User avatar

app/views/pages/home.html.erb
=> edit testimonials

app/views/ships/show.html.erb
redirected non boat owners to home page from ship#show
=> redirected non boat owners to home page from ship#show

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_popular.scss, app/assets/stylesheets/components/_testimonials.scss, app/views/pages/home.html.erb
=> Updated css on homepage

app/views/layouts/application.html.erb, config/locales/devise.en.yml
=> customized flash messages

app/views/devise/registrations/new.html.erb
=> Updated sign-up page css

app/views/layouts/application.html.erb, config/locales/simple_form.en.yml
=> changed the dismiss button style and removed ':'

app/views/ships/edit.html.erb
=> fixed buttons on edit

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
There are conflicts and I don't know why ! ah!
=> add user welcome on nav

app/views/ships/show.html.erb
=> changed boat characteristics by icons

app/assets/stylesheets/components/_carousel.scss, app/views/ships/show.html.erb
=> added border-radius and box-shadow for map and carousel

app/assets/stylesheets/components/_container.scss, app/assets/stylesheets/components/_index.scss, app/views/ships/new.html.erb
=> Updated new boat form

app/views/pages/dashboard.html.erb
=> centered booked boat card

app/views/pages/dashboard.html.erb, app/views/pages/home.html.erb, app/views/ships/index.html.erb
changed all of "ships" 🚢  to "boats"
=> change ships to boats

app/views/pages/dashboard.html.erb
=> Fixed card size and managed btn

app/views/pages/dashboard.html.erb
=> fixed image on booked boats
